---
version: "3"
services:
  neo-faucet:
    container_name: neo-faucet
    depends_on:
      - neo-scan-api
    environment:
      NEOSCAN: "neo-scan-api:4000"
    image: cityofzion/neo-local-faucet
    links:
      - "neo-scan-api:4000"
    ports:
      - "4002:4002"

  neo-privatenet1:
    container_name: neo-privatenet1
    image: cryptotuga/neo-local-privatenet:$NODE1_NEO_CLI_VERSION
    #build:
    #  context: ./privnet
    #  args:
    #    NEO_CLI_VERSION: $NODE1_NEO_CLI_VERSION
    environment:
      NODE_NUMBER: 1
    ports:
      - "20333:20333"
      - "30333:30333"

  neo-privatenet2:
    container_name: neo-privatenet2
    image: cryptotuga/neo-local-privatenet:$NODE2_NEO_CLI_VERSION
    #build:
    #  context: ./privnet
    #  args:
    #    NEO_CLI_VERSION: $NODE2_NEO_CLI_VERSION
    environment:
      NODE_NUMBER: 2
    ports:
      - "20334:20334"
      - "30334:30334"

  neo-privatenet3:
    container_name: neo-privatenet3
    image: cryptotuga/neo-local-privatenet:$NODE3_NEO_CLI_VERSION
    #build:
    #  context: ./privnet
    #  args:
    #    NEO_CLI_VERSION: $NODE3_NEO_CLI_VERSION
    environment:
      NODE_NUMBER: 3
    ports:
      - "20335:20335"
      - "30335:30335"
  
  neo-privatenet4:
    container_name: neo-privatenet4
    image: cryptotuga/neo-local-privatenet:$NODE4_NEO_CLI_VERSION
    #build:
    #  context: ./privnet
    #  args:
    #    NEO_CLI_VERSION: $NODE4_NEO_CLI_VERSION
    environment:
      NODE_NUMBER: 4
    ports:
      - "20336:20336"
      - "30336:30336"

  neo-python:
    container_name: neo-python
    depends_on:
      - neo-privatenet1
      - neo-privatenet2
      - neo-privatenet3
      - neo-privatenet4
      - neo-scan-api
      - neo-scan-sync
    image: cityofzion/neo-python:v0.8.1
    network_mode: host
    tty: true
    volumes:
      - "./smart-contracts:/smart-contracts"
      - "./wallets:/wallets"

  neo-scan-api:
    container_name: neo-scan-api
    depends_on:
    - postgres
    - neo-privatenet1
    - neo-privatenet2
    - neo-privatenet3
    - neo-privatenet4
    - notifications-server
    environment:
      HOST: "${HOST_NAME}"
      NEO_NOTIFICATIONS_SERVER: "http://${NOTIFICATIONS_SERVER}:8080/v1"
      NEO_SEEDS: "http://neo-privatenet1:30333;http://neo-privatenet2:30334;http://neo-privatenet3:30335;http://neo-privatenet4:30336"
      PORT: 4000
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: neoscan_prodv
      REPLACE_OS_VARS: "true"
    image: registry.gitlab.com/cityofzion/neo-scan/api:latest
    links:
      - "neo-privatenet1:30333"
      - "neo-privatenet2:30334"
      - "neo-privatenet3:30335"
      - "neo-privatenet4:30336"
    ports:
    - "4000:4000"

  neo-scan-sync:
    container_name: neo-scan-sync
    depends_on:
      - postgres
      - neo-privatenet1
      - neo-privatenet2
      - neo-privatenet3
      - neo-privatenet4
      - notifications-server
    environment:
      NEO_NOTIFICATIONS_SERVER: "http://${NOTIFICATIONS_SERVER}:8080/v1"
      NEO_SEEDS: "http://neo-privatenet1:30333;http://neo-privatenet2:30334;http://neo-privatenet3:30335;http://neo-privatenet4:30336"
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: neoscan_prodv
      REPLACE_OS_VARS: "true"
    image: registry.gitlab.com/cityofzion/neo-scan/sync:latest
    links:
      - "neo-privatenet1:30333"
      - "neo-privatenet2:30334"
      - "neo-privatenet3:30335"
      - "neo-privatenet4:30336"

  notifications-server:
    command: "/usr/bin/python3 /neo-python/neo/bin/api_server.py --config /neo-python/custom-config.json --port-rest 8080"
    container_name: notifications-server
    depends_on:
      - neo-privatenet1
      - neo-privatenet2
      - neo-privatenet3
      - neo-privatenet4
    image: cityofzion/neo-python
    ports:
      - "8080:8080"
    volumes:
      - "./notifications-server.config.json:/neo-python/custom-config.json"

  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
    image: "postgres:10.1"
